### ISSUE TITLE
Source Code Request

### ISSUE THREAD

**Issue by Doongka** [huynhvp/ConvLSTM-in-3D-precipitation-nowcasting#2]
Hi,
I'd like to request and discuss your source code for an upcoming research paper I am preparing.  I would like to do a comparison review of nowcasting methods and their suitability for Australian weather systems.  I have produced 2D models using ConvLSTM and TrajGRU and I'm curious to see how these stack up against your 3D models (which are thoroughly impressive!).
Cheers,
Jeff

**Comment by huynhvp** [comment]
Hi,
I am not sure that I understand correctly your question relating to 2D/3D models. In my work, input of ConvLSTM network is 3D precipitation (lon, lat, height) and the original code of ConvLSTM can adapt well this kind of input.

**Comment by alexshaodong** [comment]
> Hi,
> I'd like to request and discuss your source code for an upcoming research paper I am preparing. I would like to do a comparison review of nowcasting methods and their suitability for Australian weather systems. I have produced 2D models using ConvLSTM and TrajGRU and I'm curious to see how these stack up against your 3D models (which are thoroughly impressive!).
> Cheers,
> Jeff

Hi！Can you share the source code with me？Thx！

**Comment by huynhvp** [comment]
Hi , 
Thank you for your interest in my work. I did this work during my internship in Japan and I left everything behind after my leaving, including my code. But actually, it is mostly similar to the original one. The only difference comes from the input format (3D vs. 2D), depending on your data. Hence, I would recommend you to use the original version of ConvLSTM which is written in Theano, you can find it in the author's webpage (https://sxjscience.github.io/). From my experience, I found out that many personal works on the internet (github,...) tried to implement the idea of ConvLSTM using different frameworks (Tensorflow, Keras), but I thought they are not effective, and sometimes not correct. I think we should only rely on the original work in Theano. 
I hope this helps and good luck for your work.
