### ISSUE TITLE
it would be appreciated if you could share the source code  

### ISSUE THREAD

**Issue by SungjinChoi1128** [huynhvp/ConvLSTM-in-3D-precipitation-nowcasting#4]
I try to reach to you to ask you for sharing the source but i couldn't really find a way to contact you.
Is it possible to share ?

**Comment by huynhvp** [comment]
Hi Choi, 
Thank you for your interest in my work. I did this work during my internship in Japan and I left everything behind after my leaving, including my code. But actually, it is mostly similar to the original one. The only difference comes from the input format (3D vs. 2D), depending on your data. Hence, I would recommend you to use the original version of ConvLSTM which is written in Theano, you can find it in the author's webpage (https://sxjscience.github.io/). From my experience, I found out that many personal works on the internet (github,...) tried to implement the idea of ConvLSTM using different frameworks (Tensorflow, Keras), but I thought they are not effective, and sometimes not correct. I think we should only rely on the original work in Theano. 
I hope this helps and good luck for your work.
